### ISSUE TITLE
Faced a problem when clicking the Online Game button

### ISSUE THREAD

**Issue by bogovis** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#170]
When you click on the network game button, minecraft crashes. Here is the log: 
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-09-12 15:29:59
Description: mouseClicked event handler

java.lang.IndexOutOfBoundsException: Index: 10, Size: 9
	at net.fabricmc.fabric.impl.client.screen.ButtonList.translateIndex(ButtonList.java:123)
	at net.fabricmc.fabric.impl.client.screen.ButtonList.add(ButtonList.java:75)
	at net.fabricmc.fabric.impl.client.screen.ButtonList.add(ButtonList.java:28)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at ru.vidtu.ias.IASMinecraft.onInit(IASMinecraft.java:251)
	at ru.vidtu.ias.IASFabric.lambda$onInitializeClient$1(IASFabric.java:67)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101)
	at net.minecraft.class_437.afterInit(class_437.java:3331)
	at net.minecraft.class_437.handler$bek000$fabric-screen-api-v1$afterInitScreen(class_437.java:3284)
	at net.minecraft.class_437.method_25423(class_437.java:318)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_442.method_19860(class_442.java:154)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:295)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.redirect$dcc001$viafabricplus$storeEvent(class_312.java:4057)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
	at net.minecraft.class_310.method_1523(class_310.java:1310)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at me.deftware.weaver.Main.startGame(Main.java:119)
	at me.deftware.weaver.Main.main(Main.java:101)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.client.screen.ButtonList.translateIndex(ButtonList.java:123)
	at net.fabricmc.fabric.impl.client.screen.ButtonList.add(ButtonList.java:75)
	at net.fabricmc.fabric.impl.client.screen.ButtonList.add(ButtonList.java:28)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at ru.vidtu.ias.IASMinecraft.onInit(IASMinecraft.java:251)
	at ru.vidtu.ias.IASFabric.lambda$onInitializeClient$1(IASFabric.java:67)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101)
	at net.minecraft.class_437.afterInit(class_437.java:3331)
	at net.minecraft.class_437.handler$bek000$fabric-screen-api-v1$afterInitScreen(class_437.java:3284)
	at net.minecraft.class_437.method_25423(class_437.java:318)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_442.method_19860(class_442.java:154)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:295)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.redirect$dcc001$viafabricplus$storeEvent(class_312.java:4057)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.redirect$dcc001$viafabricplus$storeEvent(class_312.java:4057)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
	at net.minecraft.class_310.method_1523(class_310.java:1310)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at me.deftware.weaver.Main.startGame(Main.java:119)
	at me.deftware.weaver.Main.main(Main.java:101)

-- Uptime --
Details:
	JVM uptime: 68.323s
	Wall uptime: 57.770s
	High-res time: 48.780s
	Client ticks: 708 ticks / 35.400s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at me.deftware.weaver.Main.startGame(Main.java:119)
	at me.deftware.weaver.Main.main(Main.java:101)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, advanced-xray-fabric, animatica, autologin, betterfpsdist, betterstats, blur, chatanimation, chesttracker, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, conditional-mixin, craftpresence, creativecore, customsplashscreen, distanthorizons, eatinganimationid, emc, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, fastquit, freelook, fzzy_config, highlighter, ias, indium, inventoryprofilesnext, iris, itemphysic, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jade, libipn, librarian-trade-finder, litematica, macrokeybinds, malilib, midnightlib, mm, modernfix, modmenu, morechathistory, motionblur, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, now-playing, nvidium, particle-blocker, particle_core, presencefootsteps, replaymod, rrls, satin, seedcrackerx, shulkerboxtooltip, skinlayers3d, sodium, tcdcommons, viafabricplus, viewmodel, voicechat, whereisit, worldedit, xaerominimap, xaeroplus, xaeros-map-chest-tracker-integration, xaeroworldmap, yet_another_config_lib_v3, presencefootsteps:default_sound_pack, file/1_16_2_clear_gui_light_e2352.zip, file/Realistic Combat Soundpack 2.0.zip, file/dtransparent-gui-overlay-6-1-8-9.zip, file/fullhd_font_1_18_1_3.zip, file/lowonfire1.16.zip, file/alternative-particles-1-18-1.zip, file/skull-totem.zip, minecraft:supporteatinganimation, file/Better-Leaves-8.0-1.20+.zip, file/Rainbow Outlines.zip, file/White-Electric-Enchantment-Glint.zip, file/fAnimatedcRaG9BfInv.GUI1.16.5.zip, file/1-18-1-18-2-clear-gui-light.zip, file/SimpleHotbar1.21.zip, black_icons, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5284823040 bytes (5040 MiB) / 6085935104 bytes (5804 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400F
	Identifier: Intel64 Family 6 Model 151 Stepping 5
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.4617
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 32106.83
	Virtual memory used (MiB): 17518.91
	Swap memory total (MiB): 15872.00
	Swap memory used (MiB): 332.70
	Space in storage for jna.tmpdir (MiB): available: 97860.91, total: 975807.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 97860.91, total: 975807.00
	Space in storage for io.netty.native.workdir (MiB): available: 97860.91, total: 975807.00
	Space in storage for java.io.tmpdir (MiB): available: 97860.91, total: 975807.00
	Space in storage for workdir (MiB): available: 97860.91, total: 975807.00
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:-ZUncommit -XX:ZCollectionInterval=5 -XX:ZAllocationSpikeTolerance=2.0 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -Xms2048M -Xmx8192M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 21.0.0
		animatica: Animatica 0.6.1+1.21
		autologin: AutoLogin 1.2.3
		baritone: Baritone 1.10.2-5-gab84fb74
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		betterfpsdist: Better FPS distance Mod 1.21-5.1
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21
		blur: Blur+ (Fabric) 4.1.0
			midnightlib: MidnightLib 1.5.7
		chatanimation: ChatAnimation 1.0.6
		chesttracker: Chest Tracker 2.4.13+1.21.1
			whereisit: Where Is It 2.5.0+1.21
				jackfredlib: JackFredLib 0.10.0+1.21
					jackfredlib-base: JackFredLib: Base 1.4.0+1.21
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21
					jackfredlib-toasts: JackFredLib: Toasts 1.1.0+1.21
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		craftpresence: CraftPresence 2.4.2
		creativecore: CreativeCore 2.12.9
			net_neoforged_bus: bus 7.2.0
		cupboard: cupboard 1.21-2.7
		customsplashscreen: Custom Splash Screen 2.2.0
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		eatinganimationid: Eating Animation 1.21+1.9.72
		emc: EMC Framework 17.0.0
			emc-integrations: EMC Integrations 1.21
				mm: Manningham Mills 2.3
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		fabric-api: Fabric API 0.100.3+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.13+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.14+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.1+8a3b5617d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.23+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.8+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.1+cb5ced13d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.10+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.11+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.9+6573ed8cd1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.22+ab7edbacd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6bd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.4+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b3d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.79+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.14+b5597344d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.2
		fastquit: FastQuit 3.0.0+1.20.6
		freelook: Freelook 1.2.2
		fzzy_config: Fzzy Config 0.3.5+1.21
			blue_endless_jankson: jankson 1.2.3
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		highlighter: Highlighter 1.1.11
		ias: In-Game Account Switcher 9.0.1
		iceberg: Iceberg 1.2.5
		indium: Indium 1.0.33+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.3
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemphysic: ItemPhysic 1.8.0
		jade: Jade 15.1.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		libipn: libIPN 6.0.2
		librarian-trade-finder: Librarian Trade Finder 3.0.0
		litematica: Litematica 0.19.50
		macrokeybinds: Macro Keybinds 1.3.1
		malilib: MaLiLib 0.21.0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.1+mc1.21
		modmenu: Mod Menu 11.0.0
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		morechathistory: More Chat History 1.3.1
		motionblur: Motion Blur 1.0.5+mc1.21
		now-playing: Now Playing 1.5.5
		nvidium: Nvidium 0.2.8-beta
		particle-blocker: Particle Blocker 1.9
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
		particle_core: Particle Core 0.2.4+1.21
			conditional-mixin: conditional mixin 0.5.1
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		replaymod: Replay Mod 1.21-2.6.19
		rrls: Remove Reloading Screen 5.0.7+mc1.21-fabric
		satin: Satin 2.0.0
		screenshotclipboard: Screenshot to Clipboard 1.0.10
		seedcrackerx: SeedCrackerX 2.15.0
		shulkerboxtooltip: Shulker Box Tooltip 5.0.4+1.21
		skinlayers3d: 3d-Skin-Layers 1.6.7
		smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.4
		sodium: Sodium 0.5.9+mc1.21
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		viafabricplus: ViaFabricPlus 3.4.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.0.1
			com_viaversion_viaversion-common: viaversion-common 5.0.1
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.3
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.3
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.3
			io_netty_netty-codec-http: netty-codec-http 4.1.111
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_lenni0451_reflect: Reflect 1.3.2
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0
			net_raphimc_viaaprilfools: ViaAprilFools 3.0.0
			net_raphimc_viabedrock: ViaBedrock 0.0.9-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 3.0.1
			net_raphimc_vialoader: ViaLoader 3.0.1
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		viewmodel: ViewModel 2.0.0
		voicechat: Simple Voice Chat 1.21.1-2.5.21
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
		worldedit: WorldEdit 7.3.6+6892-3d660b8
		xaerominimap: Xaero's Minimap 24.3.0
		xaeroplus: XaeroPlus 2.22.3
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.2
		xaeros-map-chest-tracker-integration: Xaero's Map Chest Tracker Integration 3.0.2
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: 1.21-Aristois
	Launcher name: java-minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.17, NVIDIA Corporation
	Window size: 1920x1129
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.' x 50
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 8/8 chunks
	Resource Packs: vanilla, fabric, advanced-xray-fabric, animatica, autologin, betterfpsdist (incompatible), betterstats, blur, chatanimation, chesttracker, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, conditional-mixin, craftpresence, creativecore, customsplashscreen, distanthorizons (incompatible), eatinganimationid, emc (incompatible), enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, fastquit, freelook, fzzy_config, highlighter, ias, indium, inventoryprofilesnext, iris, itemphysic, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jade (incompatible), libipn, librarian-trade-finder, litematica, macrokeybinds, malilib, midnightlib, mm, modernfix (incompatible), modmenu, morechathistory, motionblur, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, now-playing (incompatible), nvidium, particle-blocker, particle_core, presencefootsteps, replaymod (incompatible), rrls, satin, seedcrackerx, shulkerboxtooltip, skinlayers3d, sodium, tcdcommons, viafabricplus, viewmodel, voicechat, whereisit, worldedit (incompatible), xaerominimap (incompatible), xaeroplus, xaeros-map-chest-tracker-integration, xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), presencefootsteps:default_sound_pack, file/1_16_2_clear_gui_light_e2352.zip (incompatible), file/Realistic Combat Soundpack 2.0.zip (incompatible), file/dtransparent-gui-overlay-6-1-8-9.zip (incompatible), file/fullhd_font_1_18_1_3.zip (incompatible), file/lowonfire1.16.zip (incompatible), file/alternative-particles-1-18-1.zip (incompatible), file/skull-totem.zip (incompatible), minecraft:supporteatinganimation, file/Better-Leaves-8.0-1.20+.zip, file/Rainbow Outlines.zip (incompatible), file/White-Electric-Enchantment-Glint.zip (incompatible), file/fAnimatedcRaG9BfInv.GUI1.16.5.zip (incompatible), file/1-18-1-18-2-clear-gui-light.zip (incompatible), file/SimpleHotbar1.21.zip, black_icons
	Current Language: ru_ru
	Locale: ru_RU
	System encoding: Cp1251
	File encoding: UTF-8
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400F

**Comment by VidTu** [comment]
no response.
