### ISSUE TITLE
Can't login to MS account:  Unable to convert XSTS to MCA

### ISSUE THREAD

**Issue by AriesAlex** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#173]
```
[19:49:22] [IAS/INFO]: IAS: Booting up local HTTP server...
[19:49:22] [IAS/INFO]: IAS: Bound HTTP server to 59125 port.
[19:49:22] [IAS/INFO]: IAS: HTTP server started.
[19:49:22] [Render thread/INFO]: IAS: Opening server link...
[19:50:57] [HTTP-Dispatcher/INFO]: IAS: Requested HTTP to '/'.
[19:50:57] [HTTP-Dispatcher/INFO]: IAS: Processing response...
[19:50:57] [IAS/INFO]: IAS: Extracting MSAC from query...
[19:50:57] [IAS/INFO]: IAS: Converting MSAC to MSA/MSR...
[19:50:57] [HTTP-Dispatcher/INFO]: IAS: Requested HTTP to '/end'.
[19:50:57] [IAS/INFO]: IAS: Converting MSA to XBL...
[19:50:57] [IAS/INFO]: IAS: Converting XBL to XSTS...
[19:50:58] [IAS/INFO]: IAS: Converting XSTS to MCA...
[19:50:58] [IAS/ERROR]: IAS: Create error.
java.lang.RuntimeException: Unable to create an MS account.
	at ru.vidtu.ias.auth.microsoft.MSAuthServer.lambda$auth$12(MSAuthServer.java:589) ~[IAS-Fabric-1.21-9.0.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to perform MS auth.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:994) ~[?:?]
	... 8 more
Caused by: java.lang.RuntimeException: Unable to perform MS auth.
	at ru.vidtu.ias.auth.microsoft.MSAuthServer.lambda$auth$9(MSAuthServer.java:529) ~[IAS-Fabric-1.21-9.0.1.jar:?]
	... 9 more
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to convert Xbox Secure Token Service (XSTS) token to Minecraft Access (MCA) token ((POST http://127.0.0.1:52129/https/api.minecraftservices.com/authentication/login_with_xbox) 404 with java.net.http.HttpHeaders@56fb3ec7 { {connection=[keep-alive], content-length=[9], date=[Wed, 25 Sep 2024 16:50:58 GMT]} }): Not found
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	... 7 more
Caused by: java.lang.RuntimeException: Unable to convert Xbox Secure Token Service (XSTS) token to Minecraft Access (MCA) token ((POST http://127.0.0.1:52129/https/api.minecraftservices.com/authentication/login_with_xbox) 404 with java.net.http.HttpHeaders@56fb3ec7 { {connection=[keep-alive], content-length=[9], date=[Wed, 25 Sep 2024 16:50:58 GMT]} }): Not found
	at ru.vidtu.ias.auth.microsoft.MSAuth.lambda$xstsToMca$5(MSAuth.java:491) ~[IAS-Fabric-1.21-9.0.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid status code: 404
	at ru.vidtu.ias.auth.microsoft.MSAuth.lambda$xstsToMca$5(MSAuth.java:479) ~[IAS-Fabric-1.21-9.0.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 7 more
```

I can login and play java/bedrock minecraft without mod normally but when trying to login with this mod the error appears

**Comment by VidTu** [comment]
it looks like you have a systemwide or per-app proxy (or some other mod) intercepting your requests (requests are sent to `http://127.0.0.1:52129/https/api.minecraftservices.com/authentication/login_with_xbox` instead of `https://api.minecraftservices.com/authentication/login_with_xbox`), please, try without it

**Comment by AriesAlex** [comment]
using Prism Launcher instead of UltimMC fixed the issue.
