### ISSUE TITLE
When ever I try to use the in game account switcher it says issue updating screen updates

### ISSUE THREAD

**Issue by oCub** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#20]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PlayerAPIPlugin (Player API.jar)
  Main (Old Animations.jar)
  FMLLoadingPlugin (MemoryFix.jar)
  FMLLoadingPlugin (No Close-My-Chat.jar)
  FMLLoadingPlugin (Mouse Delay FIX.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/25/20 2:45 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at the_fireplace.ias.tools.SkinTools.buildSkin(SkinTools.java:32)
	at the_fireplace.ias.gui.GuiAccountSelector.func_73866_w_(GuiAccountSelector.java:68)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
	at the_fireplace.ias.events.ClientEvents.onClick(ClientEvents.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_ClientEvents_onClick_ActionPerformedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:461)
	at net.minecraft.client.gui.GuiMainMenu.func_73864_a(GuiMainMenu.java:644)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at the_fireplace.ias.tools.SkinTools.buildSkin(SkinTools.java:32)
	at the_fireplace.ias.gui.GuiAccountSelector.func_73866_w_(GuiAccountSelector.java:68)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
	at the_fireplace.ias.events.ClientEvents.onClick(ClientEvents.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_ClientEvents_onClick_ActionPerformedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:461)
	at net.minecraft.client.gui.GuiMainMenu.func_73864_a(GuiMainMenu.java:644)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: the_fireplace.ias.gui.GuiAccountSelector
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1098581584 bytes (1047 MB) / 1677721600 bytes (1600 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_I7 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
	UCHIJA	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCHIJA	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCHIJA	perspectivemod{1.0} [Perspective Mod] ([1.8.9] Perspective Mod [fix2].jar) 
	UCHIJA	autogg{2.0.4} [Auto GG] (AutoGG-2.0.4 (1.8.9) (1).jar) 
	UCHIJA	autotip{3.0} [Autotip] (Autotip-3.0 [1.8-1.12.2].jar) 
	UCHIJA	blockoverlay{1.2} [BlockOverlay] (Block Overlay.jar) 
	UCHIJA	ChromaHUD{3.0} [Chroma HUD] (ChromaHUD-3.0.jar) 
	UCHIJA	customcrosshairmod{0.5.1-Forge} [Custom Crosshair Mod] (crosshairmod-v0.5.1-forge-mc1.8.9.jar) 
	UCHIJA	IngameAccountSwitcher{7.0.1} [In-Game Account Switcher] (InGameAccountSwitcher-Forge-1.8.9-7.0.1 (2).jar) 
	UCHIJA	keystrokesmod{1.0-SNAPSHOT} [KeystrokesMod] (KeystrokesMod-v4 [1.8.9].jar) 
	UCHIJA	macrokey{1.8.9-2.0.1.187} [MacroKey Keybinding] (MacroKey+Keybinding-1.8.9-2.0.1.187.jar) 
	UCHIJA	memoryfix{0.3} [MemoryFix] (MemoryFix.jar) 
	UCHIJA	Powns' CheatbreakerHud{1.0} [Powns' CheatbreakerHud] (Powns Cheatbreaker HUD.jar) 
	UCHIJA	ToggleSneak{3.1.4} [ToggleSneak] (Powns ToggleSneak and ToggleSprint.jar) 
	UCHIJA	sidebarmod{2.0} [Sidebar Mod Revamp] (Sidebar Mod.jar) 
	UCHIJA	LEVEL_HEAD{5.0} [Sk1er Level Head] (Sk1er Levelhead (1.8.9)-5.0.jar) 
	UCHIJA	timechanger{1.0} [TimeChanger] (Time Changer.jar) 
	UCHIJA	enhancements{7.7} [Vanilla Enhancements] (Vanilla Enhancements.jar) 
	Loaded coremods (and transformers): 
PlayerAPIPlugin (Player API.jar)
  api.player.forge.PlayerAPITransformer
Main (Old Animations.jar)
  com.spiderfrog.main.ClassTransformer
FMLLoadingPlugin (MemoryFix.jar)
  io.prplz.memoryfix.ClassTransformer
FMLLoadingPlugin (No Close-My-Chat.jar)
  com.cecer1.noclosemychat.asm.NoCloseMyChatTransformer
FMLLoadingPlugin (Mouse Delay FIX.jar)
  io.prplz.mousedelayfix.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1060 with Max-Q Design/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §8! §3Scope §832x §7Revamp.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by VidTuGit** [comment]
Should be fixed in 7.0.7.
