### ISSUE TITLE
NullPointerException while updating screen events

### ISSUE THREAD

**Issue by garzj** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#23]
Hey,

suddenly whenever I click the player head to switch my account, the game crashes with the following exception:

<details>
<summary>Expand</summary>
<p>

```
java.lang.NullPointerException: Updating screen events
	at the_fireplace.ias.tools.SkinTools.buildSkin(SkinTools.java:32)
	at the_fireplace.ias.gui.GuiAccountSelector.func_73866_w_(GuiAccountSelector.java:64)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
	at the_fireplace.ias.events.ClientEvents.onClick(ClientEvents.java:42)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_ClientEvents_onClick_ActionPerformedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:461)
	at net.minecraft.client.gui.GuiMainMenu.func_73864_a(GuiMainMenu.java:689)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

</p>
</details>

I'm using the mod with the MultiMC launcher with Forge for 1.8.9 installed.

**Comment by garzj** [comment]
Whoops, this issue was already reported.
