### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by iBikky** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#42]
My 1.12.2 forge crashes with your account switcher mod.
Here is crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  HeadlessForge (headlessforge.jar)
  Core (pingbypass-1.0.0-release.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 9/10/21 9:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from In-Game Account Switcher (ias)
Caused by: java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at the_fireplace.ias.tools.SkinTools.cacheSkins(SkinTools.java:131)
	at the_fireplace.ias.IAS.postInit(IAS.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116)
	at me.earth.headlessforge.launch.Main.main(Main.kt)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 286774264 bytes (273 MB) / 440401920 bytes (420 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                                       | Signature                                |
	|:----- |:---------- |:------------ |:-------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft  | 1.12.2       | minecraft.jar                                | None                                     |
	| LCHIJ | mcp        | 9.42         | minecraft.jar                                | None                                     |
	| LCHIJ | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIE | ias        | 7.1.1        | InGameAccountSwitcher-Forge-1.12.2-7.1.1.jar | None                                     |
	| LCHI  | pingbypass | 1.0.0        | pingbypass-1.0.0-release.jar                 | None                                     |

	Loaded coremods (and transformers): 
HeadlessForge (headlessforge.jar)
  me.earth.headlessforge.asm.HeadlessForgeTransformer
Core (pingbypass-1.0.0-release.jar)

**Comment by The-Fireplace** [comment]
Does it still crash if you remove In Game Account Switcher?

**Comment by iBikky** [comment]
When i remove the account switcher it does work

**Comment by VidTuGit** [comment]
Oh, your "HeadlessForge" removes LWJGL and OpenGL completely. I'll try to add support, but I do not guarantee this to work.

**Comment by iBikky** [comment]
How long will it take do you think

**Comment by VidTuGit** [comment]
I'm starting to fix issues rn

**Comment by VidTuGit** [comment]
It looks like it's your problem. As the author states, you [can also specify LWJGL natives path](https://github.com/3arthqu4ke/HeadlessForge#usage). In the case of In-Game Account Switcher, you MUST specify LWJGL natives' path. You can do this by adding the "-Djava.library.path" argument before "-jar". In my case, command looks like this: `java -Djava.library.path=C:\Users\VidTu\AppData\Roaming\.minecraft\versions\1.12.2-forge-14.23.5.2854\natives -jar headlessforge-1.1.jar C:\Users\VidTu\AppData\Roaming\.minecraft`.
