### ISSUE TITLE
Not working in development environment

### ISSUE THREAD

**Issue by Doogie13** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#50]
**Describe the bug**
(Forge 1.18.1)
This does not work in a dev environemt for another mod (just put in the run/mods folder)

**To Reproduce**
Open intellij and open a 1.18.1 mod
Put the account switcher in the mods folder
Run
Fail

**Logs/Screenshots/Videos**
```console
Stacktrace:
	at the_fireplace.ias.IAS.postInitialize(IAS.java:48) ~[InGameAccountSwitcher-Forge-1.18.1-7.1.3.jar%2376!:7.1.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.7.jar%239!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.7.jar%239!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.7.jar%239!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.7.jar%239!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.10.jar%2379!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.10.jar%2381!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.18.1
 - Mod Version: 7.1.3
 - Loader type: Forge
 - Loader version 39.0.10

**Comment by VidTu** [comment]
AFAIK Forge doesn't remap mods at runtime, you need to use a third-party deobfuscation tool or the `fg.deobf` (local) maven dependency.
