### ISSUE TITLE
[1.8.9] Can't login with Microsoft account

### ISSUE THREAD

**Issue by yuto0214w** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#61]
**Describe the bug**
When I try to login with Microsoft account, the error happens.

**To Reproduce**
1. Click "Add account"
2. Click "Microsoft"
3. Login

**Logs/Screenshots/Videos**
`Unknown error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

![2022-05-29_01 00 38](https://user-images.githubusercontent.com/46196561/170833369-f933a450-d1eb-40ca-97bc-e880f5019226.png)

<details><summary>Full Stacktrace</summary>

```
[01:05:20] [IAS MS Auth Thread/WARN]: Unable to auth thru MS
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1249) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1247) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1246) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[?:1.8.0_51]
	at ru.vidtu.ias.utils.Request.post(Request.java:57) ~[Request.class:?]
	at ru.vidtu.ias.utils.Auth.authXBL(Auth.java:93) ~[Auth.class:?]
	at ru.vidtu.ias.gui.MSAuthScreen.auth(MSAuthScreen.java:125) [MSAuthScreen.class:?]
	at ru.vidtu.ias.gui.MSAuthScreen.access$100(MSAuthScreen.java:35) [MSAuthScreen.class:?]
	at ru.vidtu.ias.gui.MSAuthScreen$1.lambda$handle$0(MSAuthScreen.java:61) [MSAuthScreen$1.class:?]
	at ru.vidtu.ias.gui.MSAuthScreen$1$$Lambda$14/863760835.run(Unknown Source) [MSAuthScreen$1.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[?:1.8.0_51]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:1.8.0_51]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479) ~[?:1.8.0_51]
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145) ~[?:1.8.0_51]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) ~[?:1.8.0_51]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_51]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[?:1.8.0_51]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:1.8.0_51]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479) ~[?:1.8.0_51]
	... 24 more
```

</details>

**Versions:**
 - Minecraft: 1.8.9
 - Mod Version: 7.1.3.1
 - Loader type: Forge
 - Loader version 11.15.1.2318 (latest of forge 1.8.9)

**Comment by The-Fireplace** [comment]
Have you tried the solutions listed on #53 ?

**Comment by yuto0214w** [comment]
Thank you for reply, it worked without problem.
(I would suggest adding troubleshooting to CurseForge)
